### ISSUE TITLE
You might wanna run a censorship pass on the assets.

### ISSUE THREAD

**Issue by Erquint** [skedwards88/lexlet#3]
![image](https://user-images.githubusercontent.com/4364856/209455829-a2204936-21d4-4280-b1fa-06d5007ac076.png)
https://github.com/skedwards88/palette/blob/c7666a6cd1db7f06102fcbbec93fab9ce8b500ea/src/common/wordLists/compiled/uncommonWords.json#L10152
I don't know how generation of puzzles works, but I'm suspecting that after a candidate is generated — it's validated against the assets again to make sure there's not accidentally-emerged extra words present, which would be ambiguous and give players differing results of a daily puzzle.
I suggest you move uncooth words to a blacklist instead of getting rid of them. And use that blacklist in addition to the main list when validating.

**Comment by skedwards88** [comment]
Thanks for this feedback!

The "official" solution will only use the words in `/src/common/wordLists/compiled/commonWords.json`, which excludes words like "rapers", but the game will consider any word from `src/common/wordLists/compiled/commonWords.json` or `src/common/wordLists/compiled/uncommonWords.json` valid.

I have updated the game to remove offensive words like "rapers" from both word lists. Now, the sequence of letters "rapers" may still be present, but will not be counted as a solution.
